# this should hold state (cash, position)
# also run the simulation
# this class WILL ONLY run the simulation, it will not generate signals, it will take in the signals generated by the strategy class and execute them
# we will make sure we avoid any lookahead bias by using the previous day's signal to determine the trade
# we will trade at open price of the next day after the signal is generated
class BacktestEngine:
    def __init__(self, initial_cash=100000):
        self.initial_cash = initial_cash
    def run_backtest(self, data, signals):
        # the portfolio value will be the cash we have plus the value of our position, for simplicity we will only allow 1 share to be bought/sold, and we will not track the position size or the cash separately, we will just track the total portfolio value after each trade
        # we also need to store how many shares we have 
        portfolio_value = []
        cash = self.initial_cash
        portfolio_value.append(self.initial_cash)
        position = 0
        for i in range(1, len(data)):
            # we will only buy 1 share for simplicity
            # we will use the previous day's signal to determine the trade, and we will trade at the open price of the next day
            # we will only buy if we have enough cash, and we will only sell if we have a position
            # we will update both the porfolio value and the position after each trade
            # the portfolio value will be the sum of the cash and the value of positions
            # we will calculate the value of the portfolio at the end of each day, after the trade is executed, using the close price of that day
            # the way we will calculate the portfolio is to take the cash we have and the amount of shares we have and multiply it by the close price of that day to get the total value of our position
            # then we will add that to the cash we have to get the total portfolio value
            if signals[i-1] == 1 and cash > data['open'].iloc[i] and position == 0: # buy signal and we have no position
                position += 1
                cash -= data['open'].iloc[i]
            elif signals[i-1] == -1 and position == 1: # sell signal and we have a position
                position -= 1
                cash += data['open'].iloc[i]
            # calculate portfolio value at the end of the day using the close price
            portfolio_value.append(cash + position * data['close'].iloc[i])
        return portfolio_value
