import logging
from logging_config import get_logger

logger = get_logger(__name__)

# this should hold state (cash, position)
# also run the simulation
# this class WILL ONLY run the simulation, it will not generate signals, it will take in the signals generated by the strategy class and execute them
# we will make sure we avoid any lookahead bias by using the previous day's signal to determine the trade
# we will trade at open price of the next day after the signal is generated
class BacktestEngine:
    def __init__(self, initial_cash=100000):
        self.initial_cash = initial_cash

    def run_backtest(self, data, signals):
        logger.info("Starting backtest with %s rows and initial cash %s", len(data), self.initial_cash)
        portfolio_value = []
        cash = self.initial_cash
        portfolio_value.append(self.initial_cash)
        position = 0
        for i in range(1, len(data)):
            signal = signals.iloc[i-1]
            if signal == 1 and cash > data['open'].iloc[i] and position == 0:
                position += 1
                cash -= data['open'].iloc[i]
                logger.debug("Bought 1 share at %s on row %s", data['open'].iloc[i], i)
            elif signal == -1 and position == 1:
                position -= 1
                cash += data['open'].iloc[i]
                logger.debug("Sold 1 share at %s on row %s", data['open'].iloc[i], i)
            portfolio_value.append(cash + position * data['close'].iloc[i])
        logger.info("Backtest complete. Final portfolio value %s", portfolio_value[-1])
        return portfolio_value
